[env:xiao_esp32c3]
platform  = espressif32
board     = seeed_xiao_esp32c3
framework = arduino
 
; 160 MHz gives us tighter bit-bang timing headroom
board_build.f_cpu = 160000000L
 
; USB-CDC for Serial output (required on ESP32-C3 — no UART chip on XIAO)
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
 
; Upload & monitor over USB-CDC
upload_protocol = esptool
monitor_speed   = 115200
monitor_rts = 0
monitor_dtr = 0